configuration:
  backupStorageLocations:
    - name: default
      provider: aws
      objectStorage:
        bucket: "ghassenfinal"
  volumeSnapshotLocations:
    - name: default
      provider: aws
      config:
        region: "eu-west-3"

credentials:
  useSecret: false

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.0
    volumeMounts:
      - mountPath: /target
        name: plugins

serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::949351973512:role/eks-velero-backup"
